version: '3'

services:
  product:
    build: ../mg-product-wrapper
    ports:
    - '3001:3001'

  description:
    build: ../jb-description
    ports:
    - '3003:3003'

  reviews:
    build: ../reviews-tm-service
    ports:
    - '3002:3002'

  proxy:
    build: ./
    depends_on:
      - 'product'
      - 'description'
      - 'reviews'
    ports:
      - '3333:3333'
